server.port=8080

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8070/realms/raspberry
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://keycloak:8080/realms/raspberry/protocol/openid-connect/certs
